src/libpinmame/libpinmame.cpp, src/libpinmame/libpinmame.h, src/libpinmame/test.cpp
=> libpinmame: fix dmd display type checks. Rename callbacks. Cache segments

src/libpinmame/libpinmame.cpp, src/libpinmame/libpinmame.h, src/libpinmame/test.cpp, src/wpc/mech.c, src/wpc/mech.h
This updates libpinmame to match how vpinmame handles mechs:
```
if VPINMAME
if g_fHandleMechanics
mech_updateAll 
mech_update 0 - 4
handleMech
else
mech_updateAll 
mech_update 5 - 9
else
mech_updateAll 
mech_update 0 - 4
if g_fHandleMechanics
handleMech
```
to
```
if VPINMAME || LIBPINMAME
if g_fHandleMechanics
mech_updateAll 
mech_update 0 - 4
handleMech
else
mech_updateAll 
mech_update 5 - 9
else
mech_updateAll 
mech_update 0 - 4
if g_fHandleMechanics
handleMech
```
=> mechs: fix libpinmame mechNo to match vpinmame.

src/lisy/externals.h, src/lisy/fileio.c, src/lisy/fileio.h, src/lisy/lisy.c, src/lisy/lisy1.c, src/lisy/lisy35.c, src/lisy/lisy_home.c, src/lisy/lisy_home.h, src/lisy/lisyversion.h, src/lisy/wheels.c
=> v5.78 Starship Sound & LISY1 attr act mode prep

.github/workflows/ppuc.yml
I made a mistake when merging and stashing my own branches before creating the previous PR #77.
This change should fix the build.
=> Ppuc GitHub action fix

cmake/ppuc/CMakeLists_linux-arm64.txt, cmake/ppuc/CMakeLists_linux-x64.txt, cmake/ppuc/CMakeLists_osx-x64.txt, cmake/ppuc/CMakeLists_win-x64.txt, src/ppuc/README.md, src/ppuc/dmd/dmd.cpp, src/ppuc/dmd/dmd.h, src/ppuc/pin2dmd/pin2dmd.cpp, src/ppuc/pin2dmd/pin2dmd.h, src/ppuc/ppuc.cpp, src/ppuc/serialib/serialib.cpp, src/ppuc/zedmd/zedmd.cpp, src/ppuc/zedmd/zedmd.h
Added support for https://github.com/zesinger/ZeDMD_ESP32
=> ZeDMD support for PPUC

src/ppuc/dmd/dmd.cpp, src/ppuc/dmd/dmd.h, src/ppuc/ppuc.cpp
Helps debugging PIN2DMD and ZeDMD issues.
https://www.youtube.com/watch?v=txea27RpJIY
=> PPUC: improved 2bit DMD console rendering

src/wpc/core.c, src/wpc/vpintf.c
More fixes and improvments as tests are performed on more tables. Hope this is fully good this time!
=> PWM improvments continued

src/wpc/core.c
After some more testing with existing tables, it happens that I had broken the AC integration (incorrect AC voltage wave). This fixes it.
=> PWM integration: Fix AC voltage sampling

src/sound/hc55516.c
This adds the original logic implemented in the HC55516 hardware, as determined by the 2020 decap analysis, by way of the MAME update based on the decap.  This should now be an accurate re-creation of the original chip's behavior, with exactly the same outputs as far as the on-chip DAC stage.
I've actually had this code working for a while in a side project, so I'm pretty confident in its stability as far as the new decoding algorithm goes.  I've only lightly tested this particular integration, though, just enough to make sure it's working.
The original code is still included and can be selected (it's even run-time configurable, although that's not exposed at a user level anywhere).
=> HC55516 - add original chip logic

release/whatsnew.txt, src/wpc/capcom.c
...and remove the testing leftover from Capcom
=> New PWM: update whatsnew

src/version.c
As I said, reverted for now. Will redo it in my issue the next days.
=> revert src/version.c for now (get version from version.h)

src/wpc/core.h
Fix https://github.com/vpinball/pinmame/issues/196
=> Fix WOF overlay between lamps & solenoids

src/wpc/core.h, src/wpc/vpintf.c
Fix https://github.com/vpinball/pinmame/issues/251
=> PWM: Fix internal flag being used for data exchange

src/wpc/core.c, src/wpc/wpc.c
Fix https://github.com/vpinball/pinmame/issues/271
=> Fix Stern Lamps, fix TOTAN missing PWM

src/wpc/sam.c
Fix https://github.com/vpinball/pinmame/issues/286
=> Apply flipper bat timing hack to CSI (same as IJ4)

src/cpuexec.c
Fix https://github.com/vpinball/vpinball/issues/1811
=> TimeFence: change handling to satisfy request clock while also handling master stall (like a pause)

src/sound/hc55516.c
=> hc55516: fix coincidence detection; change 55536/55564 filter params to match 55516

src/wpc/core.c, src/wpc/dmddevice.cpp
Fix https://github.com/vpinball/pinmame/issues/362
=> DMD: fix capture duplicates, add alphanum capture

src/cpu/at91/at91.c, src/wpc/sam.c
Fix https://github.com/vpinball/pinmame/issues/311
Fix https://github.com/vpinball/pinmame/issues/312
Also fix TWD lights not working after a few games
May also fix (or at least improve) SAM stability issue
=> SAM: Fix AT91 USART and add better emulation of LE nodeboards

src/wpc/wpc.c
Fix https://github.com/vpinball/pinmame/issues/359
=> WPC: Fix flipper solenoid of pre-fliptronic games

src/wpc/se.c
Fix https://github.com/vpinball/pinmame/issues/398
=> Fix Whitestar fake GameOn solenoid being constantly toggled

src/win32com/Controller.cpp, src/wpc/capcom.c, src/wpc/core.c, src/wpc/sam.c
Fix https://github.com/vpinball/pinmame/issues/404
=> PWM: fix non PWM mode for PWM only drivers

src/wpc/by35games.c, src/wpc/driver.c, src/wpc/sims/wpc/full/t2.c, src/wpc/stgames.c
Just some minor changes to update game names so they match what IPDB and OPDB use.  Verified by checking backglass and/or manuals.
=> Clean up some game names
