vpinball/pinmame

- src/common.c
- src/cpu/cop400/cop420.c
- src/dll/fileio.c
- src/dll/misc.c
- src/dll/misc.h
- src/ios/rc.c
- src/unix/config.c
- src/unix/fronthlp.c
- src/unix/xmame.h
- src/windows/misc.c
- src/windows/misc.h
- src/windows/rc.c
This PR adds linux support for libpinmame. 
After building the Linux libpinmame, there were a few undefined symbols that I was only able to track down when trying to link it against an executable. 
There was a reference to `R` which is used in cop400. 
I added some carriage returns when displaying loading information, and I removed the `Press Any Key To Continue` wait when `LIBPINMAME` is defined. 
```
VPM path: /Users/jmillard/.pinmame/
GameIndex: 2457
osd_init
osd_display_loading_rom_message(): loading mm_1_09c.bin...
osd_fopen(): access=00000000, fullpath=/Users/jmillard/.pinmame/roms/mm_109c.zip
osd_display_loading_rom_message(): loading mm_s2.1_0   ...
osd_display_loading_rom_message(): loading mm_sav3.rom ...
osd_display_loading_rom_message(): loading mm_sav4.rom ... …
```
> libpinmame: add support for linux

- .github/workflows/libpinmame.yml
This PR will trigger a repository dispatch in the pinmame-dotnet repo. 
This can be used to automatically build pinmame-dotnet, when code is pushed to this repository.
> ci: dispatch event to pinmame-dotnet repo upon successful libpinmame build

- .github/workflows/libpinmame.yml
- .github/workflows/pinmame32.yml
- PinMAME32_VC2012.vcxproj
- cmake/libpinmame/CMakeLists_linux-x64.txt
- cmake/libpinmame/CMakeLists_win-x64.txt
- cmake/libpinmame/CMakeLists_win-x86.txt
- cmake/pinmame32/CMakeLists_win-x64.txt
- cmake/pinmame32/CMakeLists_win-x86.txt
- src/ui/dialogs.c
This PR adds support for compiling win-x86 and win-x64 versions of PinMAME32 using CMake. This PR also compresses all binaries generated by the CI using UPX, except for the osx-x64 version of libpinmame. (UPX does not yet support .dylib)
Many thanks to @toxieainc for fixing errors in x64 version of PinMAME32!
> ci: add support for PinMAME32

- .github/workflows/instvpm.yml
- cmake/instvpm/CMakeLists_win-x64.txt
- cmake/instvpm/CMakeLists_win-x86.txt
- cmake/libpinmame/CMakeLists_linux-x64.txt
- cmake/libpinmame/CMakeLists_osx-x64.txt
- cmake/libpinmame/CMakeLists_win-x64.txt
- cmake/libpinmame/CMakeLists_win-x86.txt
- cmake/pinmame/CMakeLists_win-x64.txt
- cmake/pinmame/CMakeLists_win-x86.txt
- cmake/pinmame32/CMakeLists_win-x64.txt
- cmake/pinmame32/CMakeLists_win-x86.txt
- cmake/vpinmame/CMakeLists_win-x64.txt
- cmake/vpinmame/CMakeLists_win-x86.txt
- src/windows/wind3dfx.c
This PR adds support to the CI for building the VPinMAME installers. 
It also fixes a crash in the x64 version of VPinMAME where `d3d_rc_prescale` was incorrectly set as an `int` instead of a `char*`. [This code](https://github.com/vpinball/pinmame/blob/master/src/windows/rc.c#L109) was trying to free an `int`.
> ci: add support for InstallVPinMAME. Misc cmake cleanup.

- .github/workflows/prerelease.yml
- .github/workflows/vpinmame.yml
This PR allows the vpinmame artifacts to be truly a single download, run installer, and go.
> ci: add bass dlls to vpinmame artifacts

- .github/workflows/libpinmame.yml
- .github/workflows/pinmame.yml
- .github/workflows/pinmame32.yml
- .github/workflows/vpinmame.yml
- cmake/instvpm/CMakeLists_win-x64.txt
- cmake/instvpm/CMakeLists_win-x86.txt
- cmake/vpinmame/CMakeLists_win-x64.txt
- cmake/vpinmame/CMakeLists_win-x86.txt
This PR includes the following:
- rework all workflows to use `matrix` instead of multiple jobs.  
- compress binaries with `upx devel` which fixes x86 `VPinMAME.dll` failing to load in VBScript.
- adds `SAM_INCLUDE_COLORED` builds for `PinMAME`, `PinMAME32`, and `VPinMAME` 
- adds `license.txt` and `whatsnew.txt` to artifact zips.
> ci: update workflows to use matrix, upx devel, sc builds.

- src/libpinmame/libpinmame.cpp
- src/libpinmame/libpinmame.h
- src/libpinmame/test.cpp
The PR updates libpinmame:
- add missing mech flags: `STEPSW`, `LENGTHSW`
- adds Retardation (`ret`) and Acceleration (`acc`)  to `PinmameMechConfig`
- adds `PINMAME_AUDIO_FORMAT` to `PinmameConfig`
Prior to this update, `libpinmame` audio buffer was an array of `INT16`. Unity's `OnAudioFilteredRead` requests `float[]`
To request `float`, use `AUDIO_FORMAT_FLOAT`
> libpinmame: add ret and acc to mechs. add audio format to config

- .github/workflows/libpinmame.yml
- cmake/libpinmame/CMakeLists_android-arm64-v8a.txt
- cmake/libpinmame/CMakeLists_osx-arm64.txt
This PR adds support for `android-arm64-v8a`.
In addition, this PR also tweaks the compiler definition for `INLINE`.
iOS, MacOS, and Android are being compiled using clang which supports `__attribute__((always_inline))`.
> libpinmame: add support for android-arm64-v8a. Tweak INLINE define

- .github/workflows/libpinmame.yml
- .github/workflows/pinmame.yml
- .github/workflows/pinmame32.yml
- .github/workflows/prerelease.yml
- .github/workflows/vpinmame.yml
- .github/workflows/xpinmame.yml
- cmake/libpinmame/CMakeLists_osx-arm64.txt
- cmake/libpinmame/CMakeLists_osx-x64.txt
This PR updates the libpinmame workflow to build an additional set of OSX binaries that support both x64 and arm64 architectures.
> ci: merge osx libaries with lipo, other misc cleanup

- src/libpinmame/libpinmame.cpp
This PR removes the `vector_updates` variable in `libpinmame.cpp` that was required for iOS static library builds.
- not including `vector_updates` no longer causes an issue on iOS build
- fixes ci errors that are appearing for `libpinmame-android-arm64-v8a`
- fixes issue https://github.com/vpinball/pinmame/issues/58
> libpinmame: revert adding vector_updates for iOS static build

- .github/workflows/libpinmame.yml
- .github/workflows/pinmame.yml
- .github/workflows/pinmame32.yml
- .github/workflows/prerelease.yml
- .github/workflows/vpinmame.yml
- .github/workflows/xpinmame.yml
- .github/workflows/xpinmame_lisy.yml
- cmake/libpinmame/CMakeLists_ios-arm64.txt
This PR is to fix the deprecation warnings that are output during CI builds.
Also, the prerelease workflow has been modified as create-release is no longer maintained by GitHub. We now use a recommended alternative ncipollo/release-action@v1.
It also bumps fixes the failure in `libpinmame-ios-arm64` since `zlib 1.2.12` is no longer available.
> ci: update workflows to fix deprecation warnings

- src/wpc/wpc.c
When working on Twilight Zone and Creature From The Black Lagoon, I had problem with getting correct GI dimming. I noted that other existing VPX versions of these tables (and lots of WPC others) have some hacks around the GI dimming.
After some investigation, it appears that there were 3 problems with the existing implementation:
- it would use the data written to the ASIC register, filtering some of it, this hack would work as long as only one GI line would be faded but fails when there are more than one.
- it was not able to evaluate between 7 and 8 out of the 8 PWM levels (full cycle or first IRQ write)
- it was very slightly incorrect regarding fading since it takes for granted that there are 8 IRQ per Zero Cross cycle, which is wrong: it's most of the time 8 but sometimes 9 (no …
> Fix WPC GI Dimming

- src/libpinmame/libpinmame.cpp
- src/libpinmame/libpinmame.h
- src/libpinmame/test.cpp
- src/ppuc/ppuc.cpp
- src/wpc/core.c
- src/wpc/core.h
- src/wpc/vpintf.h
This PR makes the following updates to `libpinmame`:
- Adds support for `PinmameGetChangedLEDs`  (Some tables in VPinball use this to render alpha numeric displays)
- Adds support for `PinmameGetChangedSolenoids` (Useful if callback version is not wanted)
- Reworked some constants such as `PINMAME_MAX_VPM_PATH`  (Avoided cross platform collisions with `MAX_PATH`)
- Adds new state structs: `PinmameSolenoidState`, `PinmameLampState`, `PinmameGIState`, `PinmameLEDState`, and `PinmameSwitchState` (So we are not passing around arrays of `int`s and then magically indexing them)
- Adds support for getting and setting `SolMask` via `PinmameGetSolenoidMask` and `PinmameSetSolenoidMask`
- Adds support for returning modulated solenoids to `OnSolenoidUpdated` using `PinmameGetUseModulatedSolenoids` …
> libpinmame: use structs for change states, add support for SolMask, LEDs, and moduled solenoids

- src/wpc/wpc.c
I had a doubt regarding the result of my previous commit for WPC GI dimming in a few situations, so I added a high frequency inspector (will propose a PR later when it will be cleaned out) and get the following results:
(Solenoids are the top lines, GI the 5 bottom ones, sampling frequency is IRQ so around 1ms). It shows that GI is mostly ok but has some 'holes' (the 3 blue ones in the bottom line). So I checked back, @mkalkbrenner gave me this very good reference: https://github.com/bitfieldlabs/aggi/tree/master/scopes which allowed me to discover one error of my implementation. I was under the assumption the ASIC used latching logic and thyristor but in fact these are just outputs wired to Triac (which makes perfectly sense with the zero cross logic). So this PR fixes the code and is …
> Better WPC GI dimming

- src/win32com/Controller.cpp
- src/win32com/Controller.h
- src/win32com/VPinMAME.idl
- src/wpc/core.c
- src/wpc/core.h
- src/wpc/gts3.c
- src/wpc/s11.c
- src/wpc/vpintf.c
- src/wpc/vpintf.h
- src/wpc/wpc.c
Warning, this is a very lengthy PR comment since this PR contains a fairly complicated new feature that took me quite some time to (i hope) understand.
When I played with Twilight Zone, I stumbled upon 2 problems:
- GI simulation was (partly) broken and needed hacks
- Flashers were nice but dit not look true to the real table.
When I experimented with XMen, I had the same problem with (LED) flashers that I solved by pushing their power to unrealistic values but giving visually ok results. Lately, I played with CFTBL and the GI seemed broken needing hacks, and the flashers were not true to the real thing either. This added up with Guns'n Roses were flashers bulbs are directly visible to the player, and did not look about right.
After investigation, GI implementation in pinmame WPC only …
> Add PWM with user selected output device PWM integrator

- src/wpc/core.c
- src/wpc/core.h
- src/wpc/gts3.c
- src/wpc/s11.c
- src/wpc/sam.c
- src/wpc/se.c
- src/wpc/vpintf.c
- src/wpc/wpc.c
This PR:
- fix when PWM integration is used with a system that does not have modulated solenoids implemented,
- add support for WhiteStar and SAM
- performs a few cleanups
S11 is tested and fully working (with a full table configured with these new PWM outputs). Whitestar was tested with the graphic analyzer and seems good. SAM was also tested with the graphic analyzer and looks good but, perhaps, more testing for SAM (with a full table) could be interesting since the integration frequency is fairly different (4kHz instead of 1kHz for other systems)
> Improve new PWM integration

- src/wpc/core.c
- src/wpc/core.h
The initial implementation was not thread safe and could have issue (no crash, just output computation error and an error.log being generated) since:
- the emulation thread would continuously fill the sampling arrays and update sampling/zerocross pos
- the client app thread would trigger the PWM integration accessing these data without any synchronization, and requesting machine time which should only be accessed from the emulation thread while emulating a CPU.
This PR adds a simple fix by:
- specifying who is allowed to access what (emulation thread => sampling data, client thread => PWM outputs)
- do not use machine time for PWM integration any more (instead use sampling/zerocross position to compute AC wave)
- have PWM integration read the common data once, avoiding computation errors …
> PWM integration: fix multithreading issue

- cmake/libpinmame/CMakeLists_osx-arm64.txt
- cmake/libpinmame/CMakeLists_osx-x64.txt
- src/libpinmame/fileio.c
- src/libpinmame/libpinmame.cpp
- src/libpinmame/libpinmame.h
- src/libpinmame/test.cpp
- src/png.c
- src/png.h
- src/wpc/bulb.c
- src/wpc/core.c
This PR allows libpinmame to receive dmd data as brightness levels in addition to percentage values.
To use brightness levels:
```
PinmameSetDmdMode(PINMAME_DMD_MODE::BRIGHTNESS);
```
This PR also adds static builds of `libpinmame.a` for osx builds and it fixes a few duplicate symbol issues so it can be used in VPX standalone.
> libpinmame: add support for setting dmd mode (RAW/BRIGHTNESS)

- .github/workflows/ppuc.yml
This PR will fix PPUC linux builds in the CI as `libpulse0_15.99.1` was no longer available.
Still need to figure out why NASM is failing for x86 win builds.
> ci: perform apt-get update for ppuc linux builds

- .github/workflows/libpinmame.yml
- cmake/instvpm/CMakeLists_win-x64.txt
- cmake/instvpm/CMakeLists_win-x86.txt
- cmake/libpinmame/CMakeLists_win-arm64.txt
- cmake/libpinmame/CMakeLists_win-x64.txt
- cmake/libpinmame/CMakeLists_win-x86.txt
- cmake/pinmame/CMakeLists_win-x64.txt
- cmake/pinmame/CMakeLists_win-x86.txt
- cmake/pinmame32/CMakeLists_win-x64.txt
- cmake/pinmame32/CMakeLists_win-x86.txt
- cmake/ppuc/CMakeLists_win-x64.txt
- cmake/vpinmame/CMakeLists_win-x64.txt
- cmake/vpinmame/CMakeLists_win-x86.txt
The `windows-2019` images were updated on the [20230326](https://github.com/actions/runner-images/blob/win19/20230326.1/images/win/Windows2019-Readme.md). This includes a new version of CMake (3.26.1) that appears to have a different behavior when compiling assembly files using `nasm`?
The CI was failing with:
`C:\Program Files\CMake\share\cmake-3.26\Templates\MSBuild\nasm.targets(33,5): error MSB3721: The command ""C:/Users/runneradmin/nasm/nasm.exe" -o "pinmame32.dir\Release\asmblit.obj" -fwin32 -I"D:\a\pinmame\pinmame\src\\" -I"D:\a\pinmame\pinmame\src\cpu\m68000\generated_by_m68kmake\\" -I"D:\a\pinmame\pinmame\src\wpc\\" -I"D:\a\pinmame\pinmame\src\vc\\" -I"D:\a\pinmame\pinmame\src\ui\\" -I"D:\a\pinmame\pinmame\src\windows\\" -I"D:\a\pinmame\pinmame\ext\zlib\\" …
> ci: fix x86 builds due to cmake 3.26 breaking nasm compile

- src/ppuc/ppuc.cpp
Greetings, I am new! I tried to run the example from the repository and got a message about a problem related to OpenAL:
```
build/Release/ppuc -c src/ppuc/examples/t2.yml
AL lib: (EE) alc_cleanup: 1 device not closed
```
Correct roms I put on their path. There was no other error messages, just silent launch. My operating system is Linux Ubuntu 22.04.2 LTS. Then I casually familiarized myself with the code and found that call to `alcCloseDevice` is missed. Also I added 2 additional checks for `alcOpenDevice` and `alcCreateContext` calls which shuld help to diagnose the problems related to OpenAL.
> missed openAL closeDeivce call

- src/libpinmame/libpinmame.cpp
- src/libpinmame/libpinmame.h
- src/libpinmame/test.cpp
- src/ppuc/ppuc.cpp
While using libpinmame in a C++ application, there is no way to get a reference to the parent class in the callbacks without using a global static variable. 
To get around this, I've added a new void pointer `userData` to all callbacks. To not break the existing `PinmameConfig`, `userData` can be set with the new`PinmameSetUserData` function.
This PR also adds a new `SetPath` function which can be used to override `ROMS`, `NVRAM`, `SAMPLES`, `CONFIG`, and `HIGHSCORE` paths after `PinmameSetConfig` has been called.
This will be useful in iOS, where a rom may be located in the application directory, but the NVRAM file should save in the application's documents directory.
> libpinmame: new SetPath function. Added user data to callbacks.

- .gitignore
- cmake/libpinmame/CMakeLists_win-x64.txt
- cmake/libpinmame/CMakeLists_win-x86.txt
- cmake/pinmame/CMakeLists_win-x64.txt
- cmake/pinmame/CMakeLists_win-x86.txt
- cmake/pinmame32/CMakeLists_win-x64.txt
- cmake/pinmame32/CMakeLists_win-x86.txt
- cmake/ppuc/CMakeLists_win-x64.txt
- cmake/vpinmame/CMakeLists_win-x64.txt
- cmake/vpinmame/CMakeLists_win-x86.txt
- src/config.c
I've made changes to the CMake files for all Windows projects to support using the workflow scripts to generate user-level project files that successfully compile in both RELEASE and DEBUG mode.  Ultimately, this will allow project files to always stay in step with the build, and enable the removal of the project files in source control.  For now, however, it is a first step to allow DEBUG builds with minimal changes.
I had to add a non-functioning definition for logerror in the config.c file, since it is not being provided by the other projects, such as VPinMAME and was causing linking errors.  A future pull request will make this logging function work in the standalone lib.
I have tested the CMake files and confirm they build without error on my machine for all Windows projects in …
> Roscoe build fixes 20230503

- src/config.c
- win_build.bat
- win_build_help.txt
These changes include:
- Small tweak to src/windows/config.c to fix DEBUG build
- Windows batch script to automate developer builds
The script uses the same CMake scripts that the workflows use, to create Windows project files for all of the PinMAME projects.  I have tested every configuration of the build through the script (Debug, Release, Win32, x64, SAMCOLOR), and everything builds without any additional warnings or errors.  I have included comprehensive help to explain the script options.  It is accessible directly by opening the "win_build_help.txt" file as well as in-script via the "/?" option.
In theory this COULD replace the version-controlled project files that are in the repository.  Users will need to have CMake installed in addition to the normal dependencies for Visual …
> Windows universal build script

- release/whatsnew.txt
- src/wpc/altsound/altsound_file_parser.cpp
- src/wpc/altsound/altsound_processor_base.cpp
- Fixed a parsing bug for PinSound library formats
- Moved sound command log to <VPinMAME>/altsound/<ROM name> folder
- Updated "what's new" information to include AltSound changes
> Fixed parsing bug. Moved sound cmd recording output. Added release information

- src/wpc/altsound/altsound_file_parser.cpp
The original code was effectively amplifying gain values for PinSound libraries.  I did not replicate this in my new code so sound playback was muted for PinSound libraries.  This PR addresses that by restoring the same scaling factor for parsed gain values
> Restored amplification modifier for PinSound libraries

- src/wpc/altsound/altsound_csv_parser.cpp
- src/wpc/altsound/altsound_file_parser.cpp
- src/wpc/altsound/altsound_processor.cpp
- src/wpc/altsound/altsound_processor_base.cpp
- src/wpc/altsound/gsound_csv_parser.cpp
- src/wpc/altsound/gsound_processor.cpp
- src/wpc/altsound/snd_alt.cpp
- src/wpc/snd_cmd.c
This PR addresses #126 
The problem was with opening a write mail slot .  This obviously fails if PinSound Studio is not running, but we were not checking this.  We then proceed to try to open a read mail slot with a bad file handle.  This causes the code to hang in 64-bit.  By checking for the bad handle and aborting the function, the problem is resolved.
> Fixed hang if using PinSound and Studio is not running

- src/wpc/altsound/altsound_ini_processor.cpp
- src/wpc/altsound/altsound_ini_processor.hpp
- src/wpc/altsound/altsound_processor.cpp
- src/wpc/altsound/altsound_processor_base.cpp
- src/wpc/altsound/altsound_processor_base.hpp
- src/wpc/altsound/gsound_processor.cpp
- src/wpc/altsound/snd_alt.cpp
This feature was added to allow authors to specify a number of sound commands to skip at startup.  This was added to address the issue where commands are received at initialization that are valid during play, but not valid during initialization.  We don't want to ignore the command later during runtime, but we don't want to play sounds during initialization.  By specifying a skip count, 'n' commands are skipped initially, and then handled as expected once the skip count reaches 0.
> Added per-game ability to skip initial n commands

- src/wpc/altsound/altsound_ini_processor.cpp
- src/wpc/altsound/gsound_processor.cpp
Previous MUSIC sound type behavior did not allow it to stop other sound types.  This was by design, but it has been shown that the ability to allow MUSIC to stop SOLO streams would be beneficial.
> Modified MUSIC type behavior to allow STOPS

- src/wpc/core.c
From the code in wpc/core.c ,  it looks like the intent was for LIBPINMAME to use the VP Interface.
```
#if defined(VPINMAME) || defined(LIBPINMAME)  
#include "vpintf.h"
```
This PR adds the same define for core_getDip function further down in the same file
The code in win32com/Controller.cpp get_Dip and put_Dip functions also call to the VP Interface.
```
STDMETHODIMP CController::put_Dip(int nNo, int newVal)
{
// TODO: Add your implementation code here. DONE
vp_setDIP(nNo, newVal);
return S_OK;
}
```
This change at least fixes the dipswitch reading on **standalone** branch of vpinball which would not read the 
`Controller.Dip()` 
when set .
> libpinmame:  Fix Dip Switch bug in wpc/core.c

- src/cpu/m68000/m68kmame.c
- src/libpinmame/libpinmame.cpp
- src/win32com/Controller.cpp
- src/wpc/bulb.c
- src/wpc/bulb.h
- src/wpc/capcom.c
- src/wpc/capcom.h
- src/wpc/capgames.c
- src/wpc/core.c
- src/wpc/core.h
- src/wpc/gts3.c
- src/wpc/s11.c
- src/wpc/s11.h
- src/wpc/sam.c
- src/wpc/se.c
- src/wpc/sims/wpc/full/cftbl.c
- src/wpc/vpintf.c
- src/wpc/vpintf.h
- src/wpc/wpc.c
- src/wpc/wpc.h
- src/wpc/wpcgames.c
This is a rewrite of the preliminary PWM support I added at the beginning of the 3.6 phase. While using it, quite a few limitations arise, so I rewrote it to:
- Supports variable rate data writing/integration (needed for fast hardware with <1ms strobes)
- Supports high frequency controller using a linear PWM preintegration applied on high frequency data before physics model (needed for fast hardware with <1ms strobes)
- Supports strobed/PWM lamp matrix (Stern Whitestar and SAM uses this a lot, but it also improves the rendering on other hardwares)
- Supports Alphanumeric segment dimming (not yet exposed to VPinMame)
- Extended to all GI & Solenoids outputs, including aux board (WPC's GI really benefits from this, flashers wired on aux board  have been missing)
- Allow output definition …
> PWM: new implementation

- release/whatsnew.txt
- src/wpc/capcom.c
- src/wpc/core.c
- src/wpc/core.h
- src/wpc/gts3.c
- src/wpc/s11.c
- src/wpc/sam.c
- src/wpc/vpintf.c
- src/wpc/wpc.c
A new bunch of fixes for the new physic outputs.
> Generalized pwm

- src/wpc/altsound/altsound_csv_parser.cpp
Normal convention is to set the ducking value for music samples on channel 0 to 100, since music should not duck music in traditional altsound packages.  However, setting it to anything other than 100 will cause music to duck other music samples.  Setting it to 0 will completely mute other music samples, which is undesirable.  This fix will force music sample ducking to 100, ensuring proper operation.
> Fix erroneous application of ducking for music samples

- src/wpc/capcom.c
- src/wpc/core.c
- src/wpc/core.h
- src/wpc/gts3.c
- src/wpc/s11.c
- src/wpc/sam.c
- src/wpc/se.c
- src/wpc/wpc.c
This ends up the definition of all tables. The missing ones are redemption games or rare prototypes for which schematics/manual are not available (comments point to them)
Edit: also added reverted bulbs since S11 has all its AC bulbs behind relays with reversed logic
> PWM: add the last missing tables

- src/wpc/altsound/snd_alt.cpp
There is currently no support for altsound for Gottlieb games.  This became apparent with the recent release of an altsound for Alien Star (Gottlieb 1984).
I've added basic support for Gottlieb System 80A, so users can create altsounds for them.  I have confirmed that my code solves the issues seen with the Alien Star altsound package.
> Added altsound command processing support for Gottlieb System 80A

- src/wpc/altsound/snd_alt.cpp
It was brought to my attention that the Theatre of Magic altsound was exhibiting strange behavior.  On ball 1, the sounds would either not be playing or playing the incorrect sound.
After investigating this, it was discovered that code meant to signal a problem with parsing was actually causing a problem.  The details of the problem can be found [here](https://github.com/vpinball/pinmame/issues/220)
The fix involves simply removing the line of code that performs this check.  If the problem which caused this line to be necessary arises again, it should be re-evaluated and addressed with a more robust remedy.
> Altsound: Fixed bug with parsing of WPCDCS, WPCSECURITY, WPC95DCS, and WPC95 commands

- src/libpinmame/libpinmame.cpp
- src/win32com/Controller.cpp
- src/wpc/core.c
- src/wpc/core.h
This PR moves the CPU load out of the emulation thread to solve the 'stuck' flipper bats and audio glitches (audio buffer underflow ?) observed lately by some users. It seems to solve these bugs and also remove any latency caused by PWM implementation. The drawback is that the CPU loads is moved to the caller thread (for example VPX).
The algorithm used is simple enough to not require any synchronization primitive between the 2 threads. It may lead to incorrect output values on arch that do not perform float (4 bytes) read/write as a single operation. std::atomic with relaxed memory access could be used but I think this would be overkill.
Theoretically, I think there is another seldom situation that can defeat this `no sync` design which is described in the following code that would …
> PWM: perform integration on physout read instead of digital out write

- src/wpc/core.c
This bug has been there since the move of pwm integration from emulation thread to caller thread (timer_get_time is not thread safe).
I made a simple way to access the global time offset (but somewhat hacky ?). Another way would be to add direct access to the global time offset in timer.c but this would mean modifying base Mame code.
> PWM: Fix invalid timer_get_time being called from non emulation thread

- src/cpuexec.c
- src/ios/video.c
- src/libpinmame/libpinmame.cpp
- src/libpinmame/libpinmame.h
- src/libpinmame/video.c
- src/mame.h
- src/win32com/Controller.cpp
- src/win32com/Controller.h
- src/win32com/VPinMAME.idl
- src/windows/video.c
- src/wpc/vpintf.c
- src/wpc/vpintf.h
The existing implementation uses subdivided vblank (virtual ones at 60Hz) to perform emulation synchronization. This works well but can lead to some latency when used with a physic emulator like Visual Pinball X.
For example, the following MSVC Concurrency Viewer shot shows the VPinMame thread (last one above DX GPU threads). The blue part is when VPinMame is ahead of time, therefore sleeping to catch up, the green dots shows frame ticks of VPX (on a 144Hz display).
The problem is that input and physics (leading to switch triggers) can happen during these sleeping periods (with some additional latency while waiting for synchronization between VPX & VPM). Example of these are nearby optos like in XMen or Stern's Star Trek, video modes like 'Walk the Plank' in Black Rose, or flipper bats …
> Add external synchronization using a time fence

- src/cpuexec.c
- src/ios/video.c
- src/libpinmame/video.c
- src/win32com/Controller.cpp
- src/windows/video.c
- src/wpc/vpintf.c
This PR gives a cleaner implementation using semaphore allowing clean syncing. The drawback is that it contains quite a lot more modification since ti has to implement portable semaphore for PinMame. I have tested it under Windows and it works very well. For Apple & Unix device, only build have been tested since I don't have any device to run it.
> TimeFence: use semaphore instead of sleep

- src/wpc/altsound/altsound_processor.cpp
- src/wpc/altsound/altsound_processor_base.cpp
- src/wpc/altsound/altsound_processor_base.hpp
- src/wpc/altsound/gsound_processor.cpp
- src/wpc/altsound/snd_alt.cpp
@droscoe Could you please review this?
Maybe the buggy/delayed global rom volume setting is explaining your observations on weird behavior when previously using/testing this?
Also i'm not sure how to additionally tweak the new DCS global rom volume behavior. Previously, the linear volume setting used a magic '*2' for boosting, now i use a magic '*4' to compensate for the 'overall lower' volume behavior, but then i have also no clue why the previous '*2' was used.
> Fix global rom volume setting, and use verified volume behavior instead of linear for DCS

- src/wpc/bulb.c
- src/wpc/bulb.h
- src/wpc/core.c
@toxieainc these are just better bulb modelling based on real life measurements (bought a bunch of bulbs and some VPW members helped with measurements) but things are so interdependent (for example with the flicker/fusion filter) that it would be nice if you could have a look if things looks ok for you.
I have tested this with a bunch of tables supporting PWM and it looked good to me (still fading, but better for some fast blinks that I think were smoothed out by previous constants).
> Update bulb characteristic to new measures

- .gitignore
- PinMAME_VC2008.vcproj
- PinMAME_VC2012.vcxproj
- PinMAME_VC2012.vcxproj.filters
- cmake/pinmame/CMakeLists_win-x64.txt
- cmake/pinmame/CMakeLists_win-x86.txt
- cmake/xpinmame/CMakeLists_linux-x64.txt
- cmake/xpinmame/CMakeLists_osx-x64.txt
- src/driver.h
- src/unix/config.c
- src/unix/serial.c
- src/windows/config.c
- src/windows/serial.c
- src/wpc/uart_16c450.c
- src/wpc/uart_16c450.h
- src/wpc/uart_8251.c
- src/wpc/uart_8251.h
- src/wpc/uart_host.h
- src/wpc/wpc.c
- src/wpc/wpc.h
This draft pull request adds support for WPC serial ports used for printing, and for NBA Fastbreak's "Championship Link" feature.  I have emulated enough of the 8251 UART on the WPC Printer Option Kit and the 16C450 UART on the WPC95 AV board to support how the ROMs made use of them.  Related to #289.
In addition, I've added basic UART support for Windows and Unix (POSIX) platforms, based on code I wrote for another Open Source project (MPL 2.0 License).
This allows for connecting the emulated UART to a physical serial port on the host, or a virtual serial port created with a tool such as `socat` on Unix or `com0com` on Windows.
I have tested Visual Studio 2019 builds using Virtual Serial Port Driver by Electronic team, and CMake builds on macOS using XQuartz and `socat`.
I have had some …
> Support WPC UARTs (8251 from Printer Option Kit & 16C450 from WPC95)

- release/pinmame.txt
- release/whatsnew.txt
Minor documentation improvements from #290.  Provides more details in `whatsnew.txt` and adds some missing command-line options to `pinmame.txt`.
> Add documentation for -serial_device

- src/wpc/bowlgames.c
- src/wpc/core.c
- src/wpc/dmddevice.cpp
- src/wpc/gts3.c
- src/wpc/gts3.h
- src/wpc/gts3dmd.c
- src/wpc/gts3dmd.h
- src/wpc/gts3games.c
- get the same luminance levels between games,
- fix some residual flickering,
- simplify code, 
but at the price of a little performance impact
more details in `gts3dmd.c` code comment on the motivation behind this proposed change.
Note that this PR needs an update of https://github.com/vpinball/pinmame/pull/303 (I will do it if this PR is merged)
> GTS3: rewrite DMD PWM integration

- src/wpc/sims/wpc/prelim/nbaf.c
- src/wpc/wpc.c
- src/wpc/wpc.h
While moving forward with the review of the DMD code for VPX DMD renderer and following @toxieainc comment (see https://github.com/vpinball/pinmame/pull/306), 2 bugs appeared:
- DMD shading was broken on some sequence (T2 fire sequence was blinking for example),
- alpha segment where not dimming / blinking as they are on the real hardware.
This PR fixes this by:
- rewriting the FIRQ implementation: FIRQ has 3 possible sources (WPC high res timer, DMD programmable interrupt, sound board) which must be managed and acknowledged by the CPU separately. This was only (very) partially implemented. It should be ok now. It also fix the HSYNC / VSYNC rates of the DMD (122Hz)
- implementing the missing WPC high res timer. This part was made by guessing since I did not find any reference. It looks …
> WPC: implement FIRQ, implement highres timer, rewrite DMD PWM, fix alphagen dimming, fix DMD flicker

- ext/dmddevice/usbalphanumeric.h
- src/wpc/alvgdmd.c
- src/wpc/capcom.c
- src/wpc/core.c
- src/wpc/core.h
- src/wpc/dedmd.c
- src/wpc/dmddevice.cpp
- src/wpc/dmddevice.h
- src/wpc/gts3.c
- src/wpc/gts3dmd.c
- src/wpc/sam.c
- src/wpc/se.c
- src/wpc/sleic.c
- src/wpc/spinb.c
- src/wpc/wpc.c
- change dmd buffers to be linear and 0 based
- compute both luminance and bitplane DMD frames for PWM enabled drivers
- overall cleanups
> DMD: fix backward compatibility (VPX renderer, colorization plugins) and clean ups

- src/mamedbg.c
Without this change, at least with my current libc I will get a crash on the possibility that the strings overlap
> fix string overlapping in debugger command handling

- src/wpc/capcom.c
- src/wpc/sam.c
Fix https://github.com/vpinball/pinmame/issues/351
> PWM: better backward compatibility for drivers using FORCE_ON

- docs/dmd.md
- src/wpc/core.c
- src/wpc/dmddevice.cpp
- src/wpc/dmddevice.h
- src/wpc/sam.c
I limited the change to what is described in the issue #344 (it fixes #344) but I think, there is some more room for cleanup since after reviewing the codebase, there seems to be some legacy left over for dmddevice.h/dmddevice.cpp
dmddevice.h/.cpp in ext/dmddevice contains the interface for dmd device drivers: some struct definitions and some function definitions
dmddevice.h/.cpp in PinMame source contains:
- a copy of `rgb24` and `layout_t` struct from ext/dmddevice/dmddevice.h (but not the rest of it)
- an helper to get a layout to render alphanumeric on a 4:1 DMD, the implementation to actually render is in usbalphanumeric.h inside ext/dmddevice folder imported inside PinMame as well as used by ext/dmddevice drivers
- a VPinMame only definition/implementation to exchange data through …
> DMD: better backward compatibility for dmddevice.dll

- src/wpc/micropin.c
Pentacpt (the test version of pentacp2) seem to have the 7th bit (0x80) set in hardware.  This dip switch setting allows you to control this.  Both the pentacp2 and pentacpt ROMs will go into "endless tilt" mode if this is set (so, the pentacpt machine always goes into "endless tilt") in which the game will make tilt alert sounds until the game is power cycled.
> add setting to emulate pentacpt's tilt port 4 wiring

- src/vidhrdw/crtc6845.c
- src/wpc/gts3.c
Hi, 
_First (direct) contribution to **pinmame** !_
While developping a personal test ROM for GT3 MA-1739 board (DMD board) and testing it with **pinmame**, I noticed some issues related to the 6845 chip and Gottlieb SYS-3 board.
- The diag LED of the MA-1739 board is inverted. This LED has <ins>negative</ins> polarity.
- Address to read 6845 registers is wrong. $2000 need to be replaced by <ins>$2801</ins> (decoded by the U8G GAL).
- Implementation of the 6845 is erronous, as most of registers are <ins>write-only</ins> but coded read-write.
Fun to see that thoses bugs had never been detected. The main reason is that the 6845 registers are never read in pinball/video games, as they don't use cursor or lightpen capabilities.
I've also check with others 6845 variants, like MC 6845-1, MOS …
> GTS3 fix for DMD diag Led and 6845 CRTC addresses.

- src/wpc/wpc.c
Fix https://github.com/vpinball/pinmame/issues/382
> WPC: remove (again) snd FIRQ as it is not wired

- src/wpc/se.c
Fix https://github.com/vpinball/pinmame/issues/406
> Whitestar: add generic extension board handler

- src/wpc/sims/wpc/prelim/dw.c
- src/wpc/wpc.h
The game is called Doctor Who, abbreviated to DW, but not Dr. Who.
I've been spending time with the WPC-era games, and notice that most use the full name of the game.  The abbreviation to "Dr. Who" seems unnecessary.
> dw: use full name for game

- src/win32com/Controller.cpp
- src/win32com/Controller.h
- src/win32com/VPinMAME.idl
This adds a PMBuildVersion COM method to VPM similar to VPBuildVersion and B2SBuildVersion which includes the build number as decimal.
-> 3700,0012
To use this version number in Tables, there will be a method in B2S forwarding this value.
> Add new COM Version method including build number as double

- installguide/Interface.html
- release/whatsnew.txt
- src/win32com/Controller.cpp
Changed output format 3700.4711 -> 30700.4711 leaving for more minor version numbers and keeping the output similar to Visual Pinball
Added documentation to the html file and to readme.txt
> Add new COM Version method including build number as double **new format**

- cmake/vpinmame/CMakeLists_win-x64.txt
- cmake/vpinmame/CMakeLists_win-x86.txt
- vcproj/VPinMAME_VC2012.vcxproj
- vcproj/VPinMAME_VC2012.vcxproj.filters
Updating the VPinMAME build files to enable the `PINMAME_HOST_UART` feature that connects the WPC serial port to a COM port on the PC.  I was able to get a dump of FunHouse audits from Visual Pinball X for test purposes.
With this feature enabled, users can set the `serial_device` registry key to a COM port to attach to the WPC/WPC95 serial printer interface.
I used the .bat file to create a Visual Studio 2022 file from the modified 2012 files in this branch.  I have not tested building with CMake.
> wpc/uart: enable WPC UART feature in VPinMAME

- .github/workflows/vpinmame.yml
The `windows-2019` runner image was deprecated.  I bumped up to 2022, and had to update the Visual Studio version.  After doing that, I needed to remove the forced toolset of `v141_xp` in order to complete the build.
I'm not sure if the build is actually good or not, but at least it passes the build process.
Others with more CI/CMake/Visual Studio experience might want to weigh in before you merge this.
Here's the [successful workflow](https://github.com/tomlogic/pinmame/actions/runs/16328977039) on my fork.
> ci: fix VPinMAME build failures

- .github/workflows/libpinmame.yml
- .github/workflows/pinmame.yml
- .github/workflows/pinmame32.yml
- .github/workflows/prerelease.yml
- .github/workflows/vpinmame.yml
- .github/workflows/xpinmame.yml
- .github/workflows/xpinmame_lisy.yml
This PR removes upx compression to address issues like https://github.com/vpinball/pinmame/issues/472
Also, the ci has been updated to have specific `runs-on` such as `windows-2025` instead of `windows-latest`, `macos-15` instead of `macos-latest`.
This way we will know exactly what we are building on as opposed to having github automatically switch and us not knowing it:
> ci: remove upx compression to avoid virus false positives
